COUNTRY_CODES: list[str]

class SwifterError(ValueError): ...
class InvalidLength(SwifterError): ...
class InvalidStructure(SwifterError): ...
class InvalidCountryCode(SwifterError): ...
class InvalidChecksumDigits(SwifterError): ...
class InvalidBankCode(SwifterError): ...
class InvalidBranchCode(SwifterError): ...
class InvalidAccountCode(SwifterError): ...

class IBAN:
    def __init__(self, iban: str, *, allow_invalid: bool = False) -> None: ...
    @classmethod
    def from_bban(
        cls,
        country_code: str,
        bban: str,
        *,
        allow_invalid: bool = False,
    ) -> IBAN: ...
    @classmethod
    def generate(
        cls,
        country_code: str,
        *,
        bank_code: str,
        account_code: str,
        branch_code: str = "",
    ) -> IBAN: ...
    def validate(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def compact(self) -> str: ...
    @property
    def formatted(self) -> str: ...
    @property
    def country_code(self) -> str: ...
    @property
    def checksum_digits(self) -> str: ...
    @property
    def bban(self) -> str: ...
    @property
    def bank_code(self) -> str: ...
    @property
    def branch_code(self) -> str: ...
    @property
    def account_code(self) -> str: ...
    @property
    def national_checksum_digits(self) -> str: ...
    @property
    def in_sepa_zone(self) -> bool: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: IBAN | str) -> bool: ...
    def __le__(self, other: IBAN | str) -> bool: ...
    def __gt__(self, other: IBAN | str) -> bool: ...
    def __ge__(self, other: IBAN | str) -> bool: ...

class BIC:
    def __init__(self, bic: str, *, allow_invalid: bool = False) -> None: ...
    def validate(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def compact(self) -> str: ...
    @property
    def formatted(self) -> str: ...
    @property
    def bank_code(self) -> str: ...
    @property
    def country_code(self) -> str: ...
    @property
    def location_code(self) -> str: ...
    @property
    def branch_code(self) -> str: ...
    @property
    def type(self) -> str: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: BIC | str) -> bool: ...
    def __le__(self, other: BIC | str) -> bool: ...
    def __gt__(self, other: BIC | str) -> bool: ...
    def __ge__(self, other: BIC | str) -> bool: ...
