[package]
name = "swifter"
version = "1.0.0"
edition = "2021"
readme = "README.rst"

[dependencies]
pyo3 = { version = "0.29.0" }

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[lib]
name = "swifter_core"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
