from collections.abc import Callable
from typing import Any, Literal

LANGUAGES: list[str]
UNICODE_VERSION: str

def demojize(
    string: str,
    *,
    language: str = "en",
    delimiters: tuple[str, str] = (":", ":"),
) -> str: ...
def emojize(
    string: str,
    *,
    language: str = "en",
    delimiters: tuple[str, str] = (":", ":"),
    variant: Literal["text_type", "emoji_type"] | None = None,
) -> str: ...
def replace_emoji(
    string: str,
    replace: str | Callable[[str], str] | None = None,
) -> str: ...
def emoji_list(string: str) -> list[dict[str, Any]]: ...
def distinct_emoji_list(string: str) -> list[str]: ...
def emoji_count(string: str, *, unique: bool = False) -> int: ...
def is_emoji(string: str) -> bool: ...
def purely_emoji(string: str) -> bool: ...
def version(string: str) -> float: ...
def get_emoji_by_name(name: str, *, language: str = "en") -> str | None: ...
def emoji_status(string: str) -> str: ...
