from collections.abc import Iterator
from typing import Any

class Country:
    def __getattr__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...

class Subdivision:
    @property
    def country(self) -> Country: ...
    @property
    def parent(self) -> Subdivision | None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __iter__(self) -> Iterator[tuple[str, Any]]: ...

class Currency:
    def __getattr__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...

class Language:
    def __getattr__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...

class LanguageFamily:
    def __getattr__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...

class Script:
    def __getattr__(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...

class Countries:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Country]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Country: ...
    def search_fuzzy(self, query: str) -> list[Country]: ...

class HistoricCountries:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Country]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Country: ...

class Subdivisions:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Subdivision]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Subdivision | list[Subdivision]: ...
    def search_fuzzy(self, query: str) -> list[Subdivision]: ...

class Currencies:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Currency]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Currency: ...

class Languages:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Language]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Language: ...

class LanguageFamilies:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[LanguageFamily]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> LanguageFamily: ...

class Scripts:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Script]: ...
    def get(self, *, default: Any = None, **kwargs: str) -> Any: ...
    def lookup(self, value: str) -> Script: ...

countries: Countries
historic_countries: HistoricCountries
subdivisions: Subdivisions
currencies: Currencies
languages: Languages
language_families: LanguageFamilies
scripts: Scripts
