# /// script
# requires-python = ">=3.12"
# ///
"""
Generate the static Rust data tables (src/data.rs) for countryry, from the
ISO standards data maintained by Debian's |iso-codes|__ project, as shipped
in the pycountry package:

* ISO 3166-1 countries and ISO 3166-3 formerly used country names.
* ISO 3166-2 country subdivisions.
* ISO 4217 currencies.
* ISO 639-3 languages and ISO 639-5 language families.
* ISO 15924 scripts.

.. |iso-codes| replace:: ``iso-codes``
__ https://salsa.debian.org/iso-codes-team/iso-codes

The data files are read from the pinned pycountry release, downloaded from
PyPI, so that countryry's data stays identical to the pycountry version it
is tested against. pycountry ships the iso-codes data files unchanged,
except for adding each country's emoji flag.

Run with:

    uv run scripts/generate_data.py

Downloads are cached in build/downloads/.
"""

from __future__ import annotations

import json
import urllib.request
import zipfile
from pathlib import Path

# Update this to pull in new data, keeping it in sync with the pycountry
# version pinned in the test dependencies in pyproject.toml.
PYCOUNTRY_VERSION = "26.2.16"

# The datasets, in kind order, matching src/lib.rs: the Rust name prefix,
# the data file, its root key, and pycountry's non-indexed fields, whose
# values only lookup() searches, in its scan order.
DATASETS = [
    ("COUNTRY", "iso3166-1.json", "3166-1", []),
    ("HISTORIC", "iso3166-3.json", "3166-3", []),
    (
        "SUBDIVISION",
        "iso3166-2.json",
        "3166-2",
        ["name", "parent_code", "parent", "type"],
    ),
    ("CURRENCY", "iso4217.json", "4217", []),
    (
        "LANGUAGE",
        "iso639-3.json",
        "639-3",
        ["status", "scope", "type", "inverted_name", "common_name"],
    ),
    ("LANGUAGE_FAMILY", "iso639-5.json", "639-5", []),
    ("SCRIPT", "iso15924.json", "15924", []),
]

SCRIPTS_DIR = Path(__file__).parent
RUST_SRC = SCRIPTS_DIR.parent / "src"
CACHE_DIR = SCRIPTS_DIR.parent / "build" / "downloads"


def main() -> None:
    print("Downloading and combining ISO data...")
    databases = load_databases()

    out = [
        "// Generated by scripts/generate_data.py - do not edit by hand.",
        "",
        "pub const A: (u32, u32) = (u32::MAX, u32::MAX);",
        "",
    ]
    pool = Pool()
    counts = []
    for prefix, filename, root_key, no_index in DATASETS:
        entries = databases[filename][root_key]
        if prefix == "SUBDIVISION":
            entries = [subdivision_entry(entry) for entry in entries]
        out += generate_dataset(pool, prefix, entries, no_index)
        if prefix == "SUBDIVISION":
            out += generate_country_ranges(pool, entries)
        counts.append(f"{len(entries)} {root_key}")

    out[3:3] = ["pub static POOL: &str = " + rust_str(pool.data) + ";"]
    (RUST_SRC / "data.rs").write_text("\n".join(out) + "\n")
    print(
        f"data.rs: pool {len(pool.data.encode())} bytes, from pycountry "
        f"{PYCOUNTRY_VERSION}: {', '.join(counts)}."
    )


def load_databases() -> dict[str, dict[str, list[dict[str, str | None]]]]:
    """Load the ISO data files from the pinned pycountry wheel, downloading
    it from PyPI, or reusing a previous download from the cache."""
    filename = f"pycountry-{PYCOUNTRY_VERSION}-py3-none-any.whl"
    cache_path = CACHE_DIR / filename
    if not cache_path.exists():
        index = json.loads(
            download(f"https://pypi.org/pypi/pycountry/{PYCOUNTRY_VERSION}/json")
        )
        (url,) = [u["url"] for u in index["urls"] if u["filename"] == filename]
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        cache_path.write_bytes(download(url))

    databases: dict[str, dict[str, list[dict[str, str | None]]]] = {}
    with zipfile.ZipFile(cache_path) as wheel:
        for _, filename, _, _ in DATASETS:
            with wheel.open(f"pycountry/databases/{filename}") as f:
                databases[filename] = json.load(f)
    return databases


def download(url: str) -> bytes:
    print(f"  Downloading {url}")
    try:
        with urllib.request.urlopen(url) as response:
            content: bytes = response.read()
    except OSError as exc:
        raise SystemExit(f"Could not download {url}: {exc}")
    return content


def subdivision_entry(entry: dict[str, str | None]) -> dict[str, str | None]:
    """Extend a raw ISO 3166-2 entry with the fields that pycountry
    computes: the country code from the subdivision code's prefix, and the
    parent subdivision's full code, None for top-level subdivisions."""
    output: dict[str, str | None] = dict(entry)
    code = entry["code"]
    assert code is not None
    country_code = code.split("-")[0]
    parent_code = entry.get("parent")
    if parent_code is not None and parent_code.split("-")[0] != country_code:
        parent_code = f"{country_code}-{parent_code}"
    output["parent_code"] = parent_code
    output["country_code"] = country_code
    return output


def field_order(entries: list[dict[str, str | None]]) -> list[str]:
    """Field names in first-appearance order, matching the order pycountry
    creates its indices in."""
    fields: dict[str, None] = {}
    for entry in entries:
        for field in entry:
            fields.setdefault(field)
    return list(fields)


def generate_dataset(
    pool: Pool,
    prefix: str,
    entries: list[dict[str, str | None]],
    no_index: list[str],
) -> list[str]:
    fields = field_order(entries)
    special = ["country_code"] if prefix == "SUBDIVISION" else []
    indexed = [f for f in fields if f not in no_index and f not in special]
    non_indexed = [f for f in no_index if f in fields]

    data = [
        pool.add(value) if (value := entry.get(field)) is not None else None
        for entry in entries
        for field in fields
    ]

    # Sorted (lowercased value span, record index) arrays per indexed field,
    # for case-insensitive get() lookups. Where records share a value, the
    # last wins, since pycountry's index writes overwrite earlier records.
    index: list[tuple[int, int, int]] = []
    index_starts = [0]
    for field in indexed:
        by_value: dict[str, int] = {}
        for i, entry in enumerate(entries):
            value = entry.get(field)
            if value is not None:
                by_value[value.lower()] = i
        # Sorted by UTF-8 bytes, matching Rust &str ordering
        index += (
            (*pool.add(value), i)
            for value, i in sorted(by_value.items(), key=lambda kv: kv[0].encode())
        )
        index_starts.append(len(index))

    return [
        f"pub static {prefix}_FIELDS: [&str; {len(fields)}] = [{', '.join(rust_str(f) for f in fields)}];",
        spans_array(f"{prefix}_DATA", data),
        f"pub static {prefix}_INDEXED: [usize; {len(indexed)}] = [{', '.join(str(fields.index(f)) for f in indexed)}];",
        "pub static {}_INDEX: [(u32, u32, u32); {}] = [{}];".format(
            prefix, len(index), ",".join(f"({a},{b},{i})" for a, b, i in index)
        ),
        f"pub static {prefix}_INDEX_STARTS: [u32; {len(index_starts)}] = [{', '.join(str(v) for v in index_starts)}];",
        f"pub static {prefix}_NON_INDEXED: [usize; {len(non_indexed)}] = [{', '.join(str(fields.index(f)) for f in non_indexed)}];",
        "",
    ]


def generate_country_ranges(
    pool: Pool, entries: list[dict[str, str | None]]
) -> list[str]:
    """The contiguous range of subdivision records for each country, sorted
    by lowercased country code, for get(country_code=...)."""
    ranges: dict[str, tuple[int, int]] = {}
    for i, entry in enumerate(entries):
        country_code = entry["country_code"]
        assert country_code is not None
        key = country_code.lower()
        if key in ranges:
            start, end = ranges[key]
            assert end == i, f"Subdivisions of {country_code} are not contiguous"
            ranges[key] = (start, i + 1)
        else:
            ranges[key] = (i, i + 1)

    body = ",".join(
        "({},{},{},{})".format(*pool.add(key), start, end)
        for key, (start, end) in sorted(ranges.items(), key=lambda kv: kv[0].encode())
    )
    return [
        f"pub static SUBDIVISION_COUNTRY_RANGES: [(u32, u32, u32, u32); {len(ranges)}] = [{body}];",
        "",
    ]


class Pool:
    """A pool of strings concatenated for Rust span slicing, deduplicated."""

    __slots__ = ("data", "spans")

    def __init__(self) -> None:
        self.data = ""
        self.spans: dict[str, tuple[int, int]] = {}

    def add(self, string: str) -> tuple[int, int]:
        try:
            return self.spans[string]
        except KeyError:
            start = len(self.data.encode())
            span = (start, start + len(string.encode()))
            self.data += string
            self.spans[string] = span
            return span


def rust_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def spans_array(name: str, spans: list[tuple[int, int] | None]) -> str:
    body = ",".join("A" if span is None else f"({span[0]},{span[1]})" for span in spans)
    return f"pub static {name}: [(u32, u32); {len(spans)}] = [{body}];"


if __name__ == "__main__":
    main()
