# /// script
# requires-python = ">=3.12"
# ///
"""
Generate the static Rust data tables (src/data.rs) for swifter, from the
checked-in seed files in scripts/seeds/:

* iban_registry.json - the IBAN specification per country: BBAN structure,
  IBAN length, SEPA membership, and the positions of the bank code, branch
  code, account code, and national checksum digits within the BBAN.
  Derived from the SWIFT IBAN Registry, via the schwifty package.

* country_codes.json - the ISO 3166-1 alpha-2 country codes, used to
  validate the country code of BICs.

Run with uv:

    uv run scripts/generate_data.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).parent.resolve()
SEEDS = HERE / "seeds"
DATA_RS = HERE / ".." / "src" / "data.rs"

CHAR_CLASSES = {
    "n": 0,  # digits
    "a": 1,  # uppercase letters
    "c": 2,  # uppercase letters and digits
}

GROUP_RE = re.compile(r"(\d+)!([nac])")


def parse_bban_spec(spec: str) -> list[tuple[int, int]]:
    """Parse a BBAN structure like "8!n10!n" into (length, class) groups."""
    groups = []
    end = 0
    for match in GROUP_RE.finditer(spec):
        if match.start() != end:
            raise ValueError(f"Cannot parse BBAN spec: {spec!r}")
        end = match.end()
        groups.append((int(match[1]), CHAR_CLASSES[match[2]]))
    if end != len(spec):
        raise ValueError(f"Cannot parse BBAN spec: {spec!r}")
    return groups


def rust_range(positions: dict[str, list[int]], component: str) -> str:
    start, end = positions.get(component, (0, 0))
    return f"({start}, {end})"


def main() -> None:
    registry = json.loads((SEEDS / "iban_registry.json").read_text())
    country_codes = json.loads((SEEDS / "country_codes.json").read_text())

    lines = [
        "// Generated by scripts/generate_data.py - do not edit directly.",
        "",
        "pub struct IbanSpec {",
        "    pub country: &'static str,",
        "    pub iban_length: u8,",
        "    pub in_sepa_zone: bool,",
        "    // BBAN structure as (length, character class) groups, where the",
        "    // classes are 0 = digits, 1 = letters, 2 = letters and digits.",
        "    pub groups: &'static [(u8, u8)],",
        "    // Component positions within the BBAN, as (start, end) ranges.",
        "    pub bank_code: (u8, u8),",
        "    pub branch_code: (u8, u8),",
        "    pub account_code: (u8, u8),",
        "    pub national_checksum_digits: (u8, u8),",
        "}",
        "",
        "// Sorted by country code, for binary search.",
        "pub static IBAN_SPECS: &[IbanSpec] = &[",
    ]
    for country, spec in sorted(registry.items()):
        groups = parse_bban_spec(spec["bban_spec"])
        bban_length = sum(length for length, _ in groups)
        if bban_length + 4 != spec["iban_length"]:
            raise ValueError(f"Length mismatch for {country}")
        groups_rs = ", ".join(f"({length}, {cls})" for length, cls in groups)
        positions = spec["positions"]
        lines.append(
            "    IbanSpec { "
            f'country: "{country}", '
            f"iban_length: {spec['iban_length']}, "
            f"in_sepa_zone: {str(spec['in_sepa_zone']).lower()}, "
            f"groups: &[{groups_rs}], "
            f"bank_code: {rust_range(positions, 'bank_code')}, "
            f"branch_code: {rust_range(positions, 'branch_code')}, "
            f"account_code: {rust_range(positions, 'account_code')}, "
            "national_checksum_digits: "
            f"{rust_range(positions, 'national_checksum_digits')} "
            "},"
        )
    lines.extend(
        [
            "];",
            "",
            "// ISO 3166-1 alpha-2 country codes, sorted for binary search.",
            "pub static ISO3166_COUNTRIES: &[&str] = &[",
        ]
    )
    codes = sorted(country_codes)
    for start in range(0, len(codes), 12):
        row = ", ".join(f'"{code}"' for code in codes[start : start + 12])
        lines.append(f"    {row},")
    lines.extend(["];", ""])

    DATA_RS.write_text("\n".join(lines))
    print(f"Wrote {DATA_RS.resolve()}: {len(registry)} IBAN specs")


if __name__ == "__main__":
    main()
